services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DL\Benotes\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  DL\Benotes\Controller\NoteController:
    tags: ['backend.controller']

  DL\Benotes\Controller\CategoyController:
    tags: ['backend.controller']
    
